### ISSUE TITLE
Support bitbucket.org

### ISSUE THREAD

**Issue by thekid** [tueftler/doget#2]
The default configuration reads:

```yaml
repositories:
  github.com:
    url: https://github.com/{{.Vendor}}/{{.Name}}/archive/{{.Version}}.zip
```

bitbucket.org should also be supported
